name: Lint Codebase

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESlint
        run: yarn lint
